# Generated by Django 5.2.7 on 2025-11-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data", "0003_queryhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                    ("testing", "Testing"),
                ],
                default="active",
                help_text="Current connection status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the data source",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True, help_text="Last time this source was accessed", null=True
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="row_count",
            field=models.IntegerField(
                default=0, help_text="Estimated number of rows (updated on analysis)"
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="table_count",
            field=models.IntegerField(
                default=0, help_text="Number of tables available"
            ),
        ),
    ]
