# Generated by Django 5.2.7 on 2025-11-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data", "0004_alter_datasource_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gemini", "Google Gemini"),
                    ("huggingface", "Hugging Face"),
                    ("openrouter", "OpenRouter"),
                ],
                default="gemini",
                help_text="LLM model used for this query",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LLMMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("huggingface", "Hugging Face"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "success",
                    models.BooleanField(
                        default=False,
                        help_text="Si la consulta se ejecutó exitosamente",
                    ),
                ),
                (
                    "sql_generated",
                    models.TextField(
                        blank=True, help_text="SQL generado por el LLM", null=True
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Tiempo de respuesta en segundos"),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        default=0, help_text="Número de resultados retornados"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "matches_expected",
                    models.BooleanField(
                        blank=True,
                        help_text="Si el resultado coincide con el esperado (si se conoce)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Metric",
                "verbose_name_plural": "LLM Metrics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
